AWSTemplateFormatVersion: 2010-09-09
Description: 'CoreOS on EC2: http://coreos.com/docs/running-coreos/cloud-providers/ec2/'
Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AMI
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyPair
      AssociatePublicIpAddress: true
      InstanceMonitoring: false
      SecurityGroups:
      - Fn::GetAtt:
        - SecurityGroup
        - GroupId
      IamInstanceProfile:
        Ref: InstanceProfile
      UserData:
        Fn::Base64:
          Fn::Join:
          - ""
          - - |
              #cloud-config
              write_files:
                - path: /etc/ecs/ecs.config
                  permissions: "00640"
                  owner: root
                  group: root
                  permissions: 0640
                  content: |
                    ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
                    ECS_LOGFILE=/log/ecs-agent.log
                    ECS_LOGLEVEL=info
            - '      ECS_CLUSTER='
            - Ref: Cluster
            - |2

              coreos:
                units:
                  - name: amazon-ecs-agent.service
                    command: start
                    runtime: true
                    content: |
                      [Unit]
                      Description=AWS ECS Agent
                      Documentation=https://docs.aws.amazon.com/AmazonECS/latest/developerguide/
                      Requires=docker.socket
                      After=docker.socket

                      [Service]
                      Restart=on-failure
                      RestartSec=30
                      RestartPreventExitStatus=5
                      SyslogIdentifier=amazon-ecs-agent
                      ExecStartPre=-/bin/mkdir -p /var/log/ecs /var/ecs-data /etc/ecs
                      ExecStartPre=-/usr/bin/docker kill amazon-ecs-agent
                      ExecStartPre=-/usr/bin/docker rm amazon-ecs-agent
                      ExecStartPre=/usr/bin/docker pull amazon/amazon-ecs-agent:latest
                      ExecStart=/usr/bin/docker run \
                                --name amazon-ecs-agent \
                                --env-file=/etc/ecs/ecs.config \
                                --volume=/var/run/docker.sock:/var/run/docker.sock \
                                --volume=/var/log/ecs:/log \
                                --volume=/var/ecs-data:/data \
                                --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
                                --volume=/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro \
                                --publish=127.0.0.1:51678:51678 \
                                amazon/amazon-ecs-agent:latest
