wordpress:
  image: wordpress
  ports:
  - 8080:80
  mem_limit: 256m
  links:
  - mysql
  environment:
    WORDPRESS_DB_PASSWORD: ch4ngeIt0

mysql:
  image: mysql
  mem_limit: 512m
  environment:
    MYSQL_ROOT_PASSWORD: ch4ngeIt0
