---
Outputs:
  PrivateSubnetIds:
    Value:
      Fn::Join:
      - ","
      - - Ref: PrivatePrimarySubnet
        - Ref: PrivateSecondarySubnet

Resources:
  PrivatePrimarySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.3.0/24
      VpcId:
        Ref: Vpc
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs:
            Ref: AWS::Region

  PrivateSecondarySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.4.0/24
      VpcId:
        Ref: Vpc
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs:
            Ref: AWS::Region
