test1 = [1, 2, 3, 4]
test2 = 1
test3 = "hello world from input-1.json"
test5 = [13, 14, 15, 16]
test6 = 4
test7 = "hello world from input-2.yml"

[test4]
  test1 = [5, 6, 7, 8]
  test2 = 2
  test3 = "hello world from input-1.json"
  test5 = [9, 10, 11, 12]
  test6 = 3
  test7 = "hello world from input-2.yml"
