---
services:
  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: ch4ngeIt0
  wordpress:
    links:
    - mysql
    environment:
      VIRTUAL_HOST: wordpress.example.org
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ch4ngeIt0
