services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ch4ngeIt0
    image: mysql:5.5
  proxy:
    image: jwilder/nginx-proxy
    ports:
    - 80:80
    - 443:443
    restart: on-failure
    volumes:
    - //var/run/docker.sock://tmp/docker.sock:ro
  wordpress:
    environment:
      VIRTUAL_HOST: wordpress.example.org
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: ch4ngeIt0
      WORDPRESS_DB_USER: root
    image: wordpress
    links:
    - mysql
version: "2.0"
